---
configs:
  debian:
    ip: '10.0.1.10'
    box: 'debian/bullseye64'
    cpu: '2'
    ram: '4096'
    hostname: 'debian'
  controller:
    ip: '10.0.1.20'
    box: 'debian/bullseye64'
    cpu: '1'
    ram: '1024'
    hostname: 'controller'
